# Generated by Django 5.0.3 on 2024-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0002_book_category_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
