# Generated by Django 5.0.3 on 2024-03-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0005_rename_title_bookinfo_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review_content',
        ),
    ]
