# Generated by Django 5.0.3 on 2024-03-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0012_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_view_users', 'Can view users'), ('can_edit_users', 'Can edit users'), ('can_delete_users', 'Can delete users'), ('can_edit_reviews', 'Can edit reviews'), ('can_delete_reviews', 'Can delete reviews'), ('can_view_all_reviews', 'Can view all reviews'), ('can_delete_comments', 'Can delete comments'), ('can_access_admin_panel', 'Can access admin panel'), ('can_search_users_in_admin_panel', 'Can search users in admin panel'), ('can_view_user_details_in_admin_panel', 'Can view user details in admin panel'), ('can_search_reviews_in_admin_panel', 'Can search reviews in admin panel')]},
        ),
    ]
