# Generated by Django 5.0.3 on 2024-03-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0014_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='commenting',
            name='comment_text',
            field=models.TextField(max_length=50),
        ),
    ]
