# Generated by Django 5.0.3 on 2024-03-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0015_delete_book_alter_commenting_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenting',
            name='comment_text',
            field=models.TextField(max_length=100),
        ),
    ]
