# Generated by Django 5.0.3 on 2024-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0016_alter_commenting_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInfo',
        ),
    ]
