# Generated by Django 5.0.4 on 2024-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0017_bookinfo_book_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookInfo',
        ),
    ]
